SELECT * FROM Sailors, Reserves WHERE Sailors.A = Reserves.G AND Sailors.A > Reserves.G;
SELECT * FROM Sailors S;
SELECT S.A, S.B FROM Sailors S;
SELECT Sailors.A, Sailors.B FROM Sailors;
SELECT S.A FROM Sailors S;
SELECT * FROM Sailors S WHERE S.A < 3;
SELECT * FROM Sailors, Reserves WHERE Sailors.A = Reserves.G;
SELECT * FROM Sailors S1, Sailors S2 WHERE S1.A < S2.A;
SELECT DISTINCT R.G FROM Reserves R;
SELECT * FROM Sailors ORDER BY Sailors.B;
SELECT * FROM Sailors;